### ISSUE TITLE
Custom http server for next/ssr throws exception and generate duplicate styles

### ISSUE THREAD

**Issue by shobhitsharma** [modulz/stitches#320]
# Bug report

## Describe the bug

Using custom http server with next throws className mismatch exception between client and server. This probably have to do how the `react-dom/server` renderer is behaving. Styled components has solved such issue with [custom babel macro](https://github.com/styled-components/babel-plugin-styled-components) which generates server-side based style sheets.

When server is running, the styles will be duplicated and following exception will be thrown while page looking broken as css variables are overriding themselves twice.

```
Warning: Prop `className` did not match. Server: "_gVOwJd _eenzQk scid-eOeUpf" Client: "_initial_ff_gVOwJd _initial_c_eenzQk scid-eOeUpf"
    at h1
    at eval (webpack-internal:///./node_modules/@stitches/react/dist/react.esm.js:58:25)
    at styled(p) (webpack-internal:///./node_modules/@stitches/react/dist/react.esm.js:109:79)
    at div
    at eval (webpack-internal:///./node_modules/@stitches/react/dist/react.esm.js:58:25)
    at styled(div) (webpack-internal:///./node_modules/@stitches/react/dist/react.esm.js:109:79)
    at div
    at eval (webpack-internal:///./node_modules/@stitches/react/dist/react.esm.js:58:25)
    at styled(div) (webpack-internal:///./node_modules/@stitches/react/dist/react.esm.js:109:79)
    at Home
    at App (webpack-internal:///./node_modules/next/dist/pages/_app.js:76:5)
    at ErrorBoundary (webpack-internal:///./node_modules/@next/react-dev-overlay/lib/internal/ErrorBoundary.js:23:47)
    at ReactDevOverlay (webpack-internal:///./node_modules/@next/react-dev-overlay/lib/internal/ReactDevOverlay.js:73:23)
    at Container (webpack-internal:///./node_modules/next/dist/client/index.js:150:5)
    at AppContainer (webpack-internal:///./node_modules/next/dist/client/index.js:639:24)
    at Root (webpack-internal:///./node_modules/next/dist/client/index.js:764:24)
```

## To Reproduce

Check console for following codesandboxes:

example with koa: https://codesandbox.io/s/next-with-stitches-koa-bug-eip4e 
example with http-server: https://codesandbox.io/s/next-httpserver-stitches-bug-v0n78?file=/nodemon.json

## Expected behavior

This should load correct styles and avoid server mismatch by generating correct ssr based stylesheets.

## System information

- OS: macOS
- Browser (if applies) : All
- Version of Stitches: 0.0.2 and canary
- Version of Node.js: 14x

**Comment by peduarte** [comment]
We've published a pre-release of Stitches beta 🚀

**Core**:
```bash
npm install @stitches/core@0.1.0-canary.4
```

**React**:
```bash
npm install @stitches/react@0.1.0-canary.4
```

This issue should have been resolved in the beta version. We'd appreciate it if you could verify it. 

⚠️ Please refer to this [migration guide](https://stitches-site-git-beta.modulz-deploys.com/blog/migrating-from-alpha-to-beta) as there are some breaking changes.
